#!/bin/bash

echo "Let us pretend that this is building something ... and takes 20 seconds"

# Sleep for 20 seconds to simulate the build time
sleep 20

# Execute the Python script and capture its output
output=$(python3 upload_pipeline.py)

# Check if the execution was successful
if [ $? -eq 0 ]; then
    echo "Script executed successfully."
    echo "$output"
else
    echo "Failed to execute script. Check for errors."
fi


<<EOF
