#!/bin/bash

echo "Waiting for Agent!"

# Execute the Python script and capture its output
output=$(python3 upload_pipeline.py)

# Check if the execution was successful
if [ $? -eq 0 ]; then
    echo "Script executed successfully."
    echo "$output"
else
    echo "Failed to execute script. Check for errors."
fi

echo "Pipeline Built, Deployment Spec Generated!"

kubectl apply -f kubernetes_resources.yaml

echo "Deployment Spec Applied, modelled being provisioned!"


<<EOF
